name: Languages

on:
  # Run manually on demand.
  workflow_dispatch:
  push:
  # Run automatically on the first day of the month at midnight.
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update:
    name: 'Update languages'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: 'curl'

      - name: Download latest language files
        run: |
          composer dump-autoload --dev
          ./build/update-language-files

      - name: Commit changed language files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -n "$(git diff --name-only -- languages)" ]; then
            languageCount=$(git diff --name-only -- languages | wc -l)
            languageNames=$(git diff --name-only -- languages | xargs basename -a | xargs)
            dateTime=$(printf '%(%Y-%m-%d-%H-%M-%S)T')
          
            baseBranch="${{ github.ref_name }}"
            featureBranch="task-automatic-update-of-languages-${dateTime}"
            messageTitle="Automatic update of ${languageCount} languages"
            if [ "${languageCount}" -le 2 ]; then
              messageTitle="Automatic update of ${languageNames}"
            fi
            messageBody="Updated via .github/workflows/languages.yml:jobs.update."
          
            git config user.name "Martijn van der Lee"
            git config user.email "martijn@vanderlee.com"
          
            git checkout -b ${featureBranch}
            git add languages
            git commit -m "${messageTitle}" -m "${messageBody}"
            git push --set-upstream origin ${featureBranch}
          
            gh pr create --title "${messageTitle} on ${dateTime}" --body "${messageBody}" --base "${baseBranch}"
            gh pr merge --auto
          fi
