name: Languages

on:
  # Run manually on demand.
  workflow_dispatch:
  push:
  # Run automatically on the first day of the month at midnight.
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update:
    name: 'Update languages'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: 'curl'

      - name: Download latest language files
        id: download-language-files
        run: |
          composer dump-autoload --dev
          ./build/update-language-files
          
          hasChangedLanguages=0
          hasTaggedBaseBranch=0
          if [ -n "$(git diff --name-only -- languages)" ]; then
            hasChangedLanguages=1
          fi
          if [ "$(git describe --tags --abbrev=0 ${{ github.ref_name }})" = "$(git describe --tags ${{ github.ref_name }})" ]; then
            hasTaggedBaseBranch=1
          fi
          
          echo "$hasChangedLanguages"
          echo "$hasTaggedBaseBranch"
          
          echo "HAS_CHANGED_LANGUAGES=$hasChangedLanguages" >> $GITHUB_OUTPUT
          echo "HAS_TAGGED_BASE_BRANCH=$hasTaggedBaseBranch" >> $GITHUB_OUTPUT

      - name: Commit changed language files
        if: ${{ steps.download-language-files.outputs.HAS_CHANGED_LANGUAGES == 1 }}
        run: |
          baseBranch="${{ github.ref_name }}"
          featureBranch="language-update-$(printf '%(%Y-%m-%d-%H-%M-%S)T')"
          languageCount=$(git diff --name-only -- languages | wc -l)
          languageNames=$(git diff --name-only -- languages | xargs basename -a | xargs)
          
          git config --global user.name "Martijn van der Lee"
          git config --global user.email "martijn@vanderlee.com"
        
          git checkout -b ${featureBranch}
          git add languages
          if [ "${languageCount}" -le 2 ]; then
            git commit -m "Automatic update of ${languageNames}" \
                        -m "Updated via .github/workflows/languages.yml:jobs.update."
          else
            git commit -m "Automatic update of ${languageCount} languages" \
                        -m "Updated via .github/workflows/languages.yml:jobs.update."
          fi
          git push --set-upstream origin ${featureBranch}
          
      - name: Create release - if only language file updates since last release
        if: ${{ steps.download-language-files.outputs.HAS_TAGGED_BASE_BRANCH == 1 }}
        run: |
          ./build/create-release
          git push

      - name: Merge new commits into ${{ github.ref_name }} branch
        if: ${{ steps.download-language-files.outputs.HAS_CHANGED_LANGUAGES == 1 }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr create --fill --base ${{ github.ref_name }}
          gh pr merge --auto --rebase --delete-branch
