name: Tests

on:
  # Run manually on demand.
  workflow_dispatch:
  # Run automatically on every push and pull request. The runtime is only ~ 30s due to parallelization.
  push:
    # Avoid a double run for tagged commits.
    branches:
      - '*'
  pull_request:

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Include tags.
          fetch-depth: 0

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer install

      - name: Run tests
        run: |
          ./vendor/bin/phpunit

# The coverage service on https://coveralls.io requires registration of this project
# for receiving the coverage report.
#
#      - name: Run tests
#        run: |
#          ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
#
#      - name: Send coverage report to Coveralls
#        env:
#          COVERALLS_RUN_LOCALLY: 1
#          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#        run: |
#          composer require --dev php-coveralls/php-coveralls
#          ./vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v

# The code quality service on https://app.codacy.com/gh/vanderlee/phpSyllable requires
# the project registration token for receiving the coverage report.
# See: https://docs.codacy.com/getting-started/configuring-your-repository/#adding-coverage
# See: https://github.com/codacy/codacy-coverage-reporter-action.
#
#      - name: Run tests
#        run: |
#          ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
#
#      - name: Send coverage report to Codacy
#        uses: codacy/codacy-coverage-reporter-action@v1
#        with:
#          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#          coverage-reports: 'build/logs/clover.xml'